name: vitalis_bmi_calculator_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_3d_choice_chip: ^0.1.4
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1
  get: ^4.6.6
  page_transition: ^2.1.0
  pretty_gauge: ^1.0.1
  share_plus: ^10.0.2
  swipeable_button_flutter: ^0.0.3
  swipeable_button_view: ^0.0.2
  syncfusion_flutter_gauges: ^27.1.50
  syncfusion_flutter_sliders: ^27.1.50

dev_dependencies:

  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter


flutter_native_splash:
  color: "#D1D9E6"   # Color of the background of the splash screen 
  image: assets/images/splash_screen.png  # image path
  android_12:
    image: assets/images/splash_screen.png  # image path
    color: "#D1D9E6"   # Color of the background of the splash screen 



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"  # Logo image path 
  min_sdk_android: 21


flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
